name: 'Get Snyk'
description: 'Installs Snyk'
author: 'TurtleBrowser'
outputs:
  version:
    description: "The version of Snyk which was installed"
    value: ${{ steps.output_version.outputs.version }}
runs:
  using: "composite"
  steps:
    - name: Install on Mac and Linux
      id: npm_install
      run: sudo npm install -g snyk || powershell ./windows.ps1
      shell: bash
    - name: Ls
      run: ls -ltr /home/runner/
      shell: bash
    - name: Add scoop shim path to path
      run: echo "/home/runner/scoop/shims/" >> $GITHUB_PATH
      shell: bash
    - name: Fill in output variable
      id: output_version
      shell: bash
      run echo "::set-output name=version::$(snyk version)"
branding:
  icon: "crosshair"
  color: "green"
